public enum Message {
    COME_TO_EMPTY_LAND, COME_TO_SELF_LAND, COME_TO_OTHERS_LAND, PAY_PASS_FEE_SUCCESES,
    COME_TO_OTHERS_LAND_PAY_SUCCESSFUL, COME_TO_OTHERS_LAND_PAY_FAILED, COME_TO_OTHERS_LAND_WITH_MASCOT,
    COME_TO_OTHERS_LAND_WITH_OWNER_IN_PRISON, NO_ENOUGH_POINTS, AUTO_EXIT_TOOL_ROOM, COME_TO_TOOL_ROOM,
    COME_TO_GIFT_ROOM, COME_TO_PRISON, COME_TO_MINERAL_ESTATE, PUT_BLOCK_SUCCESS, NO_BLOCKS_NOW, CANT_PUT_BLOCK_WHEN_PLAYER_ON, CANT_PUT_BLOCK_WHEN_EXIST_TOOL, PUT_BOMB_SUCCESS, NO_BOMBS_NOW, CANT_PUT_BOMB_WHEN_PLAYER_ON, CANT_PUT_BOMB_WHEN_EXIST_TOOL, NULL
}
